# Generated by Django 4.2.6 on 2024-01-11 13:35

import autoslug.fields
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_wishlist_review_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
    ]
