# Generated by Django 5.0.1 on 2024-01-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='product_description',
            new_name='description',
        ),
    ]
